all:
  images:
    perWord:				8
    width:           60
    height:					60
    filetype:					png
  suspicious:
    percentageingroups:				1
    percentagepergroup:				1
  trusted:
    percentage:				10
    min:				1000
  possible:
    percentage:				50
    min:				10
