Word:
  columns:
    name:		{ type: string(255), notnull: true, unique: true }
  relations:
    Groups:
      class:	SynonymGroup
      refClass:	WordSynonymGroup
    
SynonymGroup:
  columns:
    description:	{ type: string(255), notnull: false }

WordSynonymGroup:
  columns:
    word_id:		{ type: integer, notnull: true, primary: true }
    synonym_group_id:	{ type: integer, notnull: true, primary: true }
  relations:
    Word:
      local:	word_id
      foreign:	id
      onDelete:	CASCADE
      onUpdate:	CASCADE
    SynonymGroup:
      local:	synonym_group_id
      foreign:	id
      onDelete:	CASCADE
      onUpdate:	CASCADE

Validation:
  columns:
    id:                 { type: integer(4), primary: true, autoincrement: true, unsigned: true }
    hash:               { type: string(255), notnull: true, primary: true }
    synonym_group_id:   { type: integer, notnull: true, primary: false }
  relations:
    SynonymGroup:
      local:    synonym_group_id
      foreign:  id
      onDelete: CASCADE
      onUpdate: CASCADE
